#!/usr/bin/env python3
"""Fail CI on *new* mypy errors while tolerating a frozen baseline of old ones.

Why this exists
---------------
The mypy job used to run with ``continue-on-error: true``, so it reported green
even when it failed. That mattered here more than in most repos: the test suite
substitutes ``ctx`` with a bare ``AsyncMock`` everywhere, so a regression in how
the server talks to the MCP client passes every test. When ``await`` was
stripped from 116 ``ctx.info(...)`` call sites during the mcp 2.x migration, the
suite stayed green and mypy was the only signal that caught it.

Making the job blocking outright would have turned CI red on pre-existing debt,
so instead the current errors are frozen in ``tools/mypy_baseline.txt`` and only
regressions beyond that baseline fail.

Normalization
-------------
A baseline keyed on line numbers churns on every unrelated edit above an error.
So entries are keyed on ``(file, error-code, message)`` with a count, and line
numbers are discarded. Moving code around does not touch the baseline;
introducing a new error does.

The message is part of the key, not decoration. Keyed on ``(file, code)`` alone,
two errors of the same code in one file are fungible: fixing one and
introducing a different one nets to zero and passes silently, and because a
lower count only warns (see below), the slack from an unresynced fix is
permanent headroom. The message text survives code motion exactly as well as
the code does, and it makes the baseline diff self-explanatory -- a reviewer
seeing a new line can tell what the error is without running mypy.

Comparison is deliberately asymmetric
-------------------------------------
CI runs ubuntu / py3.11 / ``pip install -e .[dev]``. A local dev venv typically
has optional extras installed too, so the two environments resolve a different
set of modules and can legitimately produce slightly different error sets. A
strict two-way ratchet would then fail on environment drift rather than on real
regressions.

    new key, or higher count  -> FAIL
    disappeared, lower count  -> warn, non-fatal, and suggest --update

That blocks regressions reliably without CI flapping. Tighten to a hard ratchet
if the drift turns out not to happen in practice.

Usage
-----
    python tools/check_mypy_baseline.py            # check, used by CI
    python tools/check_mypy_baseline.py --update   # rewrite the baseline
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "tools" / "mypy_baseline.txt"
TARGET = "src"

#: Key for one flavour of error: (posix path, error code, message).
Key = tuple[str, str, str]

# "src/foo/bar.py:123: error: Some message  [error-code]"
# Windows paths start "C:\..."; [^:] would reject the drive letter, so the file
# group allows a single-letter drive prefix explicitly.
# Note there are no CLI flags here on purpose: everything mypy needs lives in
# [tool.mypy] in pyproject.toml, so this run and a bare `mypy src` agree.
ERROR_RE = re.compile(
    r"^(?P<file>(?:[A-Za-z]:)?[^:]+):\d+:(?:\d+:)? error: "
    r"(?P<msg>.*?)\s*\[(?P<code>[a-z-]+)\]$"
)

#: mypy's own trailer. Its absence means mypy did not run to completion, which
#: must never be read as "no errors" -- see run_mypy.
SUMMARY_RE = re.compile(r"^(?:Found (?P<n>\d+) error|Success: no issues found)", re.M)

HEADER = """\
# Frozen mypy errors. Generated by tools/check_mypy_baseline.py --update.
#
# Format: <count>\t<posix-path>\t<error-code>\t<message>
#
# This file is debt, not a target. Entries should only ever be removed. If a
# line disappears because you fixed something, re-run with --update.
"""


def run_mypy() -> str:
    """Run mypy over the target and return its combined output.

    Fails closed. The obvious guard -- reject exit codes above 1 -- is not
    enough: ``python -m mypy`` exits **1** when mypy is not installed, which
    is the same code mypy uses for "found errors". The output is then empty,
    every baseline entry looks fixed, and the gate prints "OK: 0 mypy
    error(s)" and passes having checked nothing. That is the always-green
    check this script exists to delete, reached through a different door.

    So require positive evidence that mypy ran: its own summary line. That
    one check also covers an output format this parser cannot read (a future
    ``show_column_numbers``/``pretty``/``hide_error_codes``), which would
    otherwise be indistinguishable from a clean tree.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", TARGET],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=900,
    )
    output = proc.stdout + proc.stderr
    if proc.returncode not in (0, 1):
        sys.stderr.write(output)
        sys.exit(f"mypy failed to run (exit {proc.returncode}); see output above")

    summary = SUMMARY_RE.search(output)
    if summary is None:
        sys.stderr.write(output)
        sys.exit(
            "mypy produced no summary line, so it did not run to completion "
            "(not installed? crashed?). Refusing to report a clean baseline."
        )

    expected = int(summary.group("n") or 0)
    found = sum(parse(output).values())
    if found != expected:
        sys.stderr.write(output)
        sys.exit(
            f"parsed {found} error line(s) but mypy reported {expected}. The "
            "output format changed; fix ERROR_RE rather than trusting this run."
        )
    return output


def parse(output: str) -> Counter[Key]:
    """Reduce mypy output to a {(file, error-code, message): count} tally."""
    tally: Counter[Key] = Counter()
    for line in output.splitlines():
        match = ERROR_RE.match(line.strip())
        if match:
            # Windows emits backslashes; the baseline is checked in, so it has
            # to read the same on every platform.
            path = match.group("file").replace("\\", "/")
            message = " ".join(match.group("msg").split())
            tally[(path, match.group("code"), message)] += 1
    return tally


def load_baseline() -> Counter[Key]:
    tally: Counter[Key] = Counter()
    if not BASELINE_PATH.exists():
        return tally
    for lineno, raw in enumerate(
        BASELINE_PATH.read_text(encoding="utf-8").splitlines(), 1
    ):
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 4 or not parts[0].isdigit():
            sys.exit(
                f"{BASELINE_PATH.name}:{lineno}: malformed entry {line!r}. "
                "Expected <count>\\t<path>\\t<code>\\t<message>. Regenerate "
                "with --update rather than editing by hand."
            )
        count, path, code, message = parts
        tally[(path, code, message)] = int(count)
    return tally


def write_baseline(tally: Counter[Key]) -> None:
    lines = [
        f"{count}\t{path}\t{code}\t{message}"
        for (path, code, message), count in sorted(tally.items())
    ]
    BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_PATH.write_text(
        HEADER + "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from the current mypy output",
    )
    args = parser.parse_args()

    current = parse(run_mypy())

    if args.update:
        write_baseline(current)
        total = sum(current.values())
        print(f"Wrote {BASELINE_PATH.relative_to(REPO_ROOT)}: {total} errors")
        return 0

    baseline = load_baseline()

    regressions = sorted(
        (path, code, message, count - baseline.get(key, 0))
        for key, count in current.items()
        for (path, code, message) in [key]
        if count > baseline.get(key, 0)
    )
    fixed = sorted(
        (path, code, message, baseline[key] - current.get(key, 0))
        for key in baseline
        for (path, code, message) in [key]
        if current.get(key, 0) < baseline[key]
    )

    if fixed:
        print(
            f"{len(fixed)} baseline entr{'y' if len(fixed) == 1 else 'ies'} improved:"
        )
        for path, code, message, delta in fixed:
            print(f"  -{delta}  {path}  [{code}]  {message}")
        print("Run `python tools/check_mypy_baseline.py --update` to resync.\n")

    if regressions:
        new_errors = sum(delta for *_, delta in regressions)
        print(f"FAIL: {new_errors} new mypy error(s) beyond the baseline:\n")
        for path, code, message, delta in regressions:
            was = baseline.get((path, code, message), 0)
            detail = f"was {was}" if was else "new"
            print(f"  +{delta}  {path}  [{code}]  {message}  ({detail})")
        print(
            "\nFix them, or -- if they are genuinely acceptable -- run"
            "\n  python tools/check_mypy_baseline.py --update"
            "\nand explain the new entries in the commit message."
        )
        return 1

    print(f"OK: {sum(current.values())} mypy error(s), all within the baseline.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
