"""
Internationalization (i18n) module for Predictive Maintenance MCP Server.

Supports English and Chinese (Simplified) translations for report generation.
"""

from typing import Dict, Any

# Translation dictionaries
TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        # General
        "report_title": "Diagnostic Report",
        "generated_by": "Generated by",
        "server_name": "Predictive Maintenance MCP Server",
        "professional_diagnostics": "Professional machinery diagnostics and vibration analysis",
        "language": "Language",
        
        # FFT Report
        "fft_title": "FFT Spectrum Analysis",
        "sampling_rate": "Sampling Rate",
        "frequency_range": "Frequency Range",
        "signal_length": "Signal Length",
        "duration": "Duration",
        "detected_peaks": "Detected Peaks",
        "rank": "Rank",
        "frequency_hz": "Frequency (Hz)",
        "magnitude_db": "Magnitude (dB)",
        "note": "Note",
        "harmonic": "Harmonic",
        "shaft": "shaft",
        
        # Envelope Report
        "envelope_title": "Envelope Analysis",
        "filter_range": "Filter Range",
        "bearing_frequencies": "Bearing Characteristic Frequencies",
        "envelope_spectrum_peaks": "Envelope Spectrum Peaks",
        "match": "Match",
        "time_frequency_domain": "Envelope Analysis (Time + Frequency Domain)",
        "filtered_signal": "Filtered Signal",
        "envelope": "Envelope",
        "envelope_spectrum": "Envelope Spectrum",
        "amplitude": "Amplitude",
        
        # ISO Report
        "iso_title": "ISO 20816-3 Evaluation",
        "rms_velocity": "RMS Velocity",
        "evaluation_zone": "Evaluation Zone",
        "machine_group": "Machine Group",
        "support_type": "Support Type",
        "zone_boundaries": "Zone Boundaries",
        "interpretation": "Interpretation",
        "vibration_severity": "Vibration Severity",
        "new_machine_condition": "New machine condition",
        "acceptable_operation": "Acceptable operation",
        "unsatisfactory": "Unsatisfactory",
        "severe_condition": "Severe condition",
        "measured": "Measured",
        "vibration_severity_iso": "Vibration Severity according to ISO 20816-3",
        "spectrum": "Spectrum",
        "peaks": "Peaks",
        "filtered_signal": "Filtered Signal",
        "envelope": "Envelope",
        "envelope_spectrum": "Envelope Spectrum",
        "zone_a_b": "Zone A/Zone B",
        "zone_b_c": "Zone B/Zone C",
        "zone_c_d": "Zone C/Zone D",
        "new_machine": "New machine condition",
        "acceptable": "Acceptable operation",
        "unsatisfactory_condition": "Unsatisfactory",
        "severe": "Severe condition",
        "new": "New",
        "acceptable_level": "Acceptable",
        "unsatisfactory_level": "Unsatisfactory",
        "severe_level": "Severe",
        "zone_description_new": "The machine is in new condition, vibration levels are very low.",
        "zone_description_acceptable": "The measured vibration level is within acceptable limits for this machine class.",
        "zone_description_unsatisfactory": "The vibration level is higher than acceptable. Maintenance should be planned.",
        "zone_description_severe": "The vibration level is dangerously high. Immediate action is required.",
        
        # Integrated Diagnostic Report
        "diagnostic_report": "Diagnostic Report",
        "evidence": "Evidence",
        "evidence_strength": "Evidence strength",
        "indicators_disagree": "Indicators disagree",
        "bearing_frequency_matching": "Bearing frequency matching",
        "calculated_against_measured": "Calculated against measured",
        "element": "Element",
        "calculated": "Calculated",
        "measured_hz": "Measured",
        "deviation": "Deviation",
        "verdict": "Verdict",
        "match_found": "match",
        "no_match": "no match",
        "envelope_spectrum_chart": "Envelope spectrum",
        "no_envelope_figure": "This report carries no envelope spectrum figure, so the frequency match cannot be checked visually here — only against the values in the table above.",
        "anomaly_detection": "Anomaly detection",
        "spectral_energy_distribution": "Spectral energy distribution",
        "comparison_with_baseline": "Comparison with baseline",
        "recommended_actions": "Recommended actions",
        "why": "Why",
        "evidence_label": "Evidence",
        "provenance": "Provenance",
        "signal": "Signal",
        "shaft_speed_rpm": "Shaft speed (RPM)",
        "bearing": "Bearing",
        "iso_machine_group_support": "ISO machine group / support",
        "server_version": "Server version",
        "generated": "Generated",
        "to_resolve": "To resolve",
        "iso_severity": "ISO severity",
        "low": "low",
        "medium": "medium",
        "high": "high",
        "critical": "critical",
        "assessed": "assessed",
        "refused": "refused",
        "absent": "absent",
        "rigid": "rigid",
        "flexible": "flexible",
        # Dynamic content translations
        "machine_condition": "Machine condition",
        "rms_velocity": "RMS velocity",
        "iso_zone": "ISO zone",
        "severity": "Severity",
        "bpfo_frequency": "BPFO frequency",
        "plan_maintenance": "Plan maintenance",
        "inspect_bearing": "Inspect bearing",
        "monitor_condition": "Monitor condition",
        "inspection": "inspection",
        "new_machine_condition": "New machine condition",
        "acceptable_operation": "Acceptable operation",
        "unsatisfactory": "Unsatisfactory",
        "severe_condition": "Severe condition",
        "zone_a": "Zone A",
        "zone_b": "Zone B",
        "zone_c": "Zone C",
        "zone_d": "Zone D",
        # Advisory content translations
        "moderate": "moderate",
        "strong": "strong",
        "weak": "weak",
        "zone": "Zone",
        "rms_velocity_value": "RMS velocity: {value} mm/s",
        "iso_zone_value": "ISO zone: {zone}",
        "severity_value": "Severity: {severity}",
        "iso_evaluation_indicates": "ISO evaluation indicates",
        "with_severity_level": "with severity level",
        "anomaly_ratio": "Anomaly ratio",
        "energy_concentrated": "Energy concentrated at bearing fault frequencies.",
        "new": "New",
        "acceptable": "Acceptable",
        "severe": "Severe",
        # Additional translations for integrated report
        "no_baseline_available": "No baseline available for comparison.",
        "schedule_bearing_inspection": "Schedule bearing inspection",
        "visual_inspection": "Visual inspection of bearing condition.",
        "iso_zone_c_indicates": "ISO zone C indicates attention needed.",
        
        # DOCX Report
        "diagnostic_report_docx": "Diagnostic Report",
        "statistical_summary": "Statistical Summary",
        "parameter": "Parameter",
        "value": "Value",
        "fft_spectrum_top_peaks": "FFT Spectrum — Top Peaks",
        "frequency": "Frequency",
        "magnitude": "Magnitude",
        "envelope_analysis_top_peaks": "Envelope Analysis — Top Peaks",
        "bearing_match": "Bearing Match",
        "bearing_characteristic_frequencies": "Bearing Characteristic Frequencies",
        "frequency_label": "Frequency",
        "value_hz": "Value (Hz)",
        "iso_20816_evaluation": "ISO 20816-3 Evaluation",
        "diagnostic_summary": "Diagnostic Summary",
        "thresholds": "Thresholds",
        
        # Plot Signal Report
        "plot_signal_title": "Time-Domain Signal",
        "statistics_overlay": "Statistical reference lines: RMS (green dashed), Peak (red dotted), Mean (orange dash-dot)",
        "time_s": "Time (s)",
        "signal": "Signal",
        "rms": "RMS",
        "peak_pos": "Peak (+)",
        "peak_neg": "Peak (−)",
        "mean": "Mean",
        
        # PCA Report
        "pca_title": "PCA Visualization",
        "model_name": "Model",
        "total_segments": "Total Segments",
        "total_anomalies": "Anomalies",
        "anomaly_ratio": "Anomaly Ratio",
        "pca_variance": "Variance Explained",
        "total_variance": "Total (2D)",
        "validation_metrics": "Validation Metrics",
        "overall_accuracy": "Overall Accuracy",
        "correct_predictions": "Correct Predictions",
        "predicted_healthy": "Predicted: Healthy",
        "predicted_anomaly": "Predicted: Anomaly",
        
        # Feature Comparison Report
        "feature_comparison_title": "Time-Domain Feature Comparison",
        "num_groups": "Groups",
        "num_features": "Features",
        "segments": "segments",
        "healthy": "Healthy",
        "faulty": "Faulty",
        
        # Status messages
        "fft_report_saved": "FFT spectrum report saved",
        "envelope_report_saved": "Envelope analysis report saved",
        "iso_report_saved": "ISO 20816-3 report saved",
        "diagnostic_report_saved": "Diagnostic report saved",
        "docx_report_saved": "DOCX report saved",
        
        # Severity zones
        "zone_a": "Zone A",
        "zone_b": "Zone B",
        "zone_c": "Zone C",
        "zone_d": "Zone D",
        
        # Common
        "hz": "Hz",
        "mm_s": "mm/s",
        "seconds": "s",
        "kilobytes": "KB",
    },
    "zh": {
        # General
        "report_title": "诊断报告",
        "generated_by": "生成者",
        "server_name": "预测性维护MCP服务器",
        "professional_diagnostics": "专业机械诊断和振动分析",
        "language": "语言",
        
        # FFT Report
        "fft_title": "FFT频谱分析",
        "sampling_rate": "采样率",
        "frequency_range": "频率范围",
        "signal_length": "信号长度",
        "duration": "持续时间",
        "detected_peaks": "检测到的峰值",
        "rank": "排名",
        "frequency_hz": "频率 (Hz)",
        "magnitude_db": "幅值 (dB)",
        "note": "备注",
        "harmonic": "谐波",
        "shaft": "轴",
        
        # Envelope Report
        "envelope_title": "包络分析",
        "filter_range": "滤波范围",
        "bearing_frequencies": "轴承特征频率",
        "envelope_spectrum_peaks": "包络谱峰值",
        "match": "匹配",
        "time_frequency_domain": "包络分析（时域 + 频域）",
        "filtered_signal": "滤波信号",
        "envelope": "包络",
        "envelope_spectrum": "包络谱",
        "amplitude": "幅值",
        
        # ISO Report
        "iso_title": "ISO 20816-3 评估",
        "rms_velocity": "均方根速度",
        "evaluation_zone": "评估区域",
        "machine_group": "机器组别",
        "support_type": "支撑类型",
        "zone_boundaries": "区域边界",
        "interpretation": "解释说明",
        "vibration_severity": "振动严重程度",
        "new_machine_condition": "新机器状态",
        "acceptable_operation": "可接受运行",
        "unsatisfactory": "不满意",
        "severe_condition": "严重状态",
        "measured": "测量值",
        "vibration_severity_iso": "根据ISO 20816-3的振动严重程度",
        "spectrum": "频谱",
        "peaks": "峰值",
        "filtered_signal": "滤波信号",
        "envelope": "包络",
        "envelope_spectrum": "包络谱",
        "zone_a_b": "A区/B区",
        "zone_b_c": "B区/C区",
        "zone_c_d": "C区/D区",
        "new_machine": "新机器状态",
        "acceptable": "可接受运行",
        "unsatisfactory_condition": "不满意",
        "severe": "严重状态",
        "new": "新",
        "acceptable_level": "可接受",
        "unsatisfactory_level": "不满意",
        "severe_level": "严重",
        "zone_description_new": "机器处于新状态，振动水平非常低。",
        "zone_description_acceptable": "测量的振动水平在该机器类别的可接受范围内。",
        "zone_description_unsatisfactory": "振动水平高于可接受范围。应计划维护。",
        "zone_description_severe": "振动水平危险地高。需要立即采取行动。",
        
        # Integrated Diagnostic Report
        "diagnostic_report": "诊断报告",
        "evidence": "证据",
        "evidence_strength": "证据强度",
        "indicators_disagree": "指标不一致",
        "bearing_frequency_matching": "轴承频率匹配",
        "calculated_against_measured": "计算值与测量值对比",
        "element": "元件",
        "calculated": "计算值",
        "measured_hz": "测量值",
        "deviation": "偏差",
        "verdict": "判定",
        "match_found": "匹配",
        "no_match": "不匹配",
        "envelope_spectrum_chart": "包络谱",
        "no_envelope_figure": "本报告未包含包络谱图，因此无法在此直观检查频率匹配情况——只能与上表中的数值进行对比。",
        "anomaly_detection": "异常检测",
        "spectral_energy_distribution": "频谱能量分布",
        "comparison_with_baseline": "与基线对比",
        "recommended_actions": "建议措施",
        "why": "原因",
        "evidence_label": "证据",
        "provenance": "来源信息",
        "signal": "信号",
        "shaft_speed_rpm": "轴转速 (RPM)",
        "bearing": "轴承",
        "iso_machine_group_support": "ISO机器组别 / 支撑类型",
        "server_version": "服务器版本",
        "generated": "生成时间",
        "to_resolve": "解决方法",
        "iso_severity": "ISO 严重程度",
        "low": "低",
        "medium": "中",
        "high": "高",
        "critical": "严重",
        "assessed": "已评估",
        "refused": "已拒绝",
        "absent": "缺失",
        "rigid": "刚性",
        "flexible": "柔性",
        # Dynamic content translations
        "machine_condition": "机器状态",
        "rms_velocity": "均方根速度",
        "iso_zone": "ISO区域",
        "severity": "严重程度",
        "bpfo_frequency": "BPFO频率",
        "plan_maintenance": "计划维护",
        "inspect_bearing": "检查轴承",
        "monitor_condition": "监测状态",
        "inspection": "检查",
        "new_machine_condition": "新机器状态",
        "acceptable_operation": "可接受运行",
        "unsatisfactory": "不满意",
        "severe_condition": "严重状态",
        "zone_a": "A区",
        "zone_b": "B区",
        "zone_c": "C区",
        "zone_d": "D区",
        # Advisory content translations
        "moderate": "中等",
        "strong": "强",
        "weak": "弱",
        "zone": "区域",
        "rms_velocity_value": "均方根速度: {value} mm/s",
        "iso_zone_value": "ISO区域: {zone}",
        "severity_value": "严重程度: {severity}",
        "iso_evaluation_indicates": "ISO评估表明",
        "with_severity_level": "严重程度为",
        "anomaly_ratio": "异常比例",
        "energy_concentrated": "能量集中在轴承故障频率。",
        "new": "新",
        "acceptable": "可接受",
        "severe": "严重",
        # Additional translations for integrated report
        "no_baseline_available": "没有可用于比较的基线。",
        "schedule_bearing_inspection": "安排轴承检查",
        "visual_inspection": "目视检查轴承状况。",
        "iso_zone_c_indicates": "ISO区域C表示需要注意。",
        
        # DOCX Report
        "diagnostic_report_docx": "诊断报告",
        "statistical_summary": "统计摘要",
        "parameter": "参数",
        "value": "值",
        "fft_spectrum_top_peaks": "FFT频谱 — 主要峰值",
        "frequency": "频率",
        "magnitude": "幅值",
        "envelope_analysis_top_peaks": "包络分析 — 主要峰值",
        "bearing_match": "轴承匹配",
        "bearing_characteristic_frequencies": "轴承特征频率",
        "frequency_label": "频率",
        "value_hz": "值 (Hz)",
        "iso_20816_evaluation": "ISO 20816-3 评估",
        "diagnostic_summary": "诊断摘要",
        "thresholds": "阈值",
        
        # Plot Signal Report
        "plot_signal_title": "时域信号",
        "statistics_overlay": "统计参考线：均方根 (绿色虚线)、峰值 (红色点线)、均值 (橙色点划线)",
        "time_s": "时间 (s)",
        "signal": "信号",
        "rms": "均方根",
        "peak_pos": "峰值 (+)",
        "peak_neg": "峰值 (−)",
        "mean": "均值",
        
        # PCA Report
        "pca_title": "PCA 可视化",
        "model_name": "模型",
        "total_segments": "总片段数",
        "total_anomalies": "异常数",
        "anomaly_ratio": "异常比例",
        "pca_variance": "方差解释",
        "total_variance": "总计 (2D)",
        "validation_metrics": "验证指标",
        "overall_accuracy": "总体准确率",
        "correct_predictions": "正确预测数",
        "predicted_healthy": "预测：健康",
        "predicted_anomaly": "预测：异常",
        
        # Feature Comparison Report
        "feature_comparison_title": "时域特征对比",
        "num_groups": "分组数",
        "num_features": "特征数",
        "segments": "个片段",
        "healthy": "健康",
        "faulty": "故障",
        
        # Status messages
        "fft_report_saved": "FFT频谱报告已保存",
        "envelope_report_saved": "包络分析报告已保存",
        "iso_report_saved": "ISO 20816-3报告已保存",
        "diagnostic_report_saved": "诊断报告已保存",
        "docx_report_saved": "DOCX报告已保存",
        
        # Severity zones
        "zone_a": "A区",
        "zone_b": "B区",
        "zone_c": "C区",
        "zone_d": "D区",
        
        # Common
        "hz": "Hz",
        "mm_s": "mm/s",
        "seconds": "秒",
        "kilobytes": "KB",
    }
}


class I18n:
    """Internationalization helper for report generation."""
    
    def __init__(self, language: str = "en"):
        """
        Initialize i18n with a language.
        
        Args:
            language: Language code ('en' or 'zh')
        """
        self.language = language if language in TRANSLATIONS else "en"
    
    def t(self, key: str) -> str:
        """
        Get translation for a key.
        
        Args:
            key: Translation key
            
        Returns:
            Translated string, or key itself if not found
        """
        return TRANSLATIONS.get(self.language, {}).get(key, key)
    
    def get_language(self) -> str:
        """Get current language code."""
        return self.language
    
    def set_language(self, language: str) -> None:
        """
        Set language.
        
        Args:
            language: Language code ('en' or 'zh')
        """
        if language in TRANSLATIONS:
            self.language = language


def get_i18n(language: str = "en") -> I18n:
    """
    Factory function to get an i18n instance.
    
    Args:
        language: Language code ('en' or 'zh')
        
    Returns:
        I18n instance
    """
    return I18n(language)
